### PR TITLE
Season5/nearer my god to thee

### PR DESCRIPTION
**Pull request by Jim-Duke**
Ready for review.  I have added the rules to the Makefile.  So it should be easier to add additional songs from here on out.

### CODE REVIEW

**Comment by nocollier** [comment]
I went through each part on the score and listened to a few follow the music. This looks good to me. Wow who is going to hold the high C?!

**Review by nocollier — APPROVED** [review]

**Comment by nocollier** [comment]
What song should I do next? I glanced through the list of issues and didn't see any more links to pdfs, can you point me to the right source and I will keep at it? :)

**Comment by Jim-Duke** [comment]
I know, right!  Maybe my son Michael – he can’t do it in full voice; but he has a VERY powerful falsetto; and it’s his impression that the BYU singer is singing that last note in falsetto.  I’m trying to get him to join us; he sang with us in the past.  Easily the most talented singer in my family.

And did you notice the low C’s the Bass II’s have?

**Comment by Jim-Duke** [comment]
I added comments to Hold On, and When You Believe with links to the sheet music.  Pick whichever one you want.

I have the sheet music to Ezekiel; but for the rest, we’ll need to wait for the sheet music to arrive.

**Pull request merged**
